service: quiz-app

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1
  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    WEBSOCKET_ENDPOINT:
      !Join [
        "",
        [
          "wss://",
          Ref: WebsocketsApi,
          ".execute-api.${AWS::Region}.amazonaws.com/dev",
        ],
      ]
  websocketsApiName: QuizWebsocketApi
  websocketsApiRouteSelectionExpression: $request.body.action

functions:
  graphql:
    handler: src/handlers/graphqlHandler.handler
    events:
      - http:
          path: graphql
          method: post

  websocketConnect:
    handler: src/handlers/websocketHandler.connect
    events:
      - websocket:
          route: $connect

  websocketDisconnect:
    handler: src/handlers/websocketHandler.disconnect
    events:
      - websocket:
          route: $disconnect

  websocketDefault:
    handler: src/handlers/websocketHandler.default
    events:
      - websocket:
          route: $default

resources:
  Resources:
    WebsocketsApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: WebsocketsApi
        ProtocolType: WEBSOCKET
        RouteSelectionExpression: $request.body.action

    McqTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: McqTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    SessionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SessionTable
        AttributeDefinitions:
          - AttributeName: sessionId
            AttributeType: S
        KeySchema:
          - AttributeName: sessionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
